package com.posterpdf.data.backend

object BackendConfig {
    // Replace with your Firebase Functions HTTPS URL once deployed.
    // Example: https://us-central1-<project-id>.cloudfunctions.net/api
    const val BASE_URL = "https://us-central1-static-webbing-461904-c4.cloudfunctions.net/api"

    // OAuth 2.0 Web client ID from Firebase Console -> Authentication -> Sign-in providers -> Google.
    // Required for GoogleSignIn.requestIdToken(...) to mint a token Firebase Auth will accept.
    // Auto-generated by Firebase when Google sign-in was enabled (2026-05-02);
    // mirrors the client_type=3 entry in app/google-services.json.
    const val WEB_CLIENT_ID = "403450695023-r57lj4c1dtnb906bh84totam87712m3p.apps.googleusercontent.com"
}
